cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

ogs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('users.urls', namespace='users')),
    path('', include('products.urls', namespace='products')),
    path('accounts/', include('django.contrib.auth.urls')),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
    path('order_list/', views.order_list, name='order_list'),
]

products/urls.py
from django.conf.urls.static import static
from django.urls import path
from . import views
from django.conf import settings

app_name = 'products'

urlpatterns = [
    path('product_list/', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('product/create/', views.product_new, name='product_new'),
    path('product/<int:pk>/edit/', views.product_edit, name='product_edit'),
    path('product/<int:pk>/delete/', views.product_delete, name='product_delete'),
    path('category/create/', views.category_new, name='category_new'),
    path('category/<int:pk>/edit/', views.category_edit, name='category_edit'),
    path('category/view/', views.category_list_emp, name='category_list_emp'),
    path('category/<int:pk>/delete/', views.category_delete, name='category_delete'),
    path('onlinegrocery/employee_home/', views.employee_home, name='employee_home'),
    path('onlinegrocery/home/', views.home, name='home'),
    path('onlinegrocery/contact_page/', views.visitor_new, name='visitor_new'),
    path('fruits/', views.product_list, name='product_list_by_category'),






]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from . import views
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

app_name = 'users'


urlpatterns = [
    re_path(r'register_customer/', views.register_customer, name='register_customer'),
    path('edit/<int:pk>', views.edit_customer, name='edit_customer'),
    path('customer_list/', views.customer_list, name='customer_list'),
    path('', views.home, name='home'),
    re_path(r'^home/$', views.home, name='home'),
    path('about_page/', views.about, name='about'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('faq_page/', views.faq, name='faq'),
    # path('', include('django.contrib.auth.urls')),
    path('password_reset_form/',
         auth_views.PasswordResetView.as_view(),
         name='password_reset_form'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('users/password_change/',
         auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html'),
         name='password_change'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
    ]

users/models.py
from django.contrib.auth.models import AbstractUser, AbstractBaseUser
from django.db import models
from django.urls import reverse


class User(AbstractUser):
    is_customer = models.BooleanField(default=False)
    phone = models.CharField(max_length=20, null=False)


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, related_name="customer")

    def __str__(self):
        return self.user.username

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import Customer, User


class CustomerSignUpForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = User
        fields = ('first_name', 'last_name', 'email', 'phone', 'username', 'password1', 'password2')

    def save(self):
        user = super().save(commit=False)
        user.is_customer = True
        user.save()
        Customer.objects.create(user=user)
        return user


class CustomerForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'phone')

users/views.py
from itertools import product

from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.template.context_processors import csrf
from django.utils import timezone
from django.views.generic import ListView

from cart.forms import CartAddProductForm
from orders.models import Order
from products.filter import ProductFilter
from products.forms import CategoryForm
from products.models import Category, Product
from .models import *
from .forms import *


now = timezone.now()


def home(request):
    return render(request, 'onlinegrocery/onlinegrocery_homepage.html',
                  {'users': home})


def register_customer(request):
    if request.method == 'POST':
        form = CustomerSignUpForm(request.POST)
        if form.is_valid():
            form.save()
            if request.user.is_superuser:
                return redirect('users:customer_list')
            else:
                return render(request, 'registration/registration_done.html')
    args = {}
    args.update(csrf(request))
    args['form'] = CustomerSignUpForm()
    return render(request, 'registration/customer_registration_form.html', args)


@login_required
def edit_customer(request, pk):
    customer = get_object_or_404(User, pk=pk)
    if request.method == "POST":
        # update
        form = CustomerForm(request.POST, instance=customer)
        if form.is_valid():
            customer = form.save(commit=False)
            customer.save()
            return redirect('products:product_list')
    else:
        # edit
        form = CustomerForm(instance=customer)
    return render(request, 'registration/customer_edit.html', {'form': form})


def customer_list(request):
    customers = User.objects.filter(is_customer=True)
    return render(request, 'customer_list.html',
                  {'customers': customers})


def about(request):
    return render(request, 'onlinegrocery/about_page.html',
                  {'about': about})


def faq(request):
    return render(request, 'onlinegrocery/faq_page.html',
                  {'faq': faq})


def login(request):
    return render(request, 'registration/login.html',
                  {'login': login})

users/templates/onlinegrocery/about_page.html
<!DOCTYPE html>
<html lang="en">
{% extends 'onlinegrocery/base.html' %}
{%load static %}
{% block content %}

<h1 class="headings"> About Us</h1>
<div id="main-container">
    <div id="about-container">
        <div id="about-image-container">
            <img src={% static "img/aboutus.png" %} alt="whiteTshirt">
        </div>
        <div id="about-description">

            <p>
                What started small, with a single discount store and the simple idea of selling more for less,
                has grown over the last 50 years into the largest retailer in the world.
                Each week, nearly 230 million customers and members visit approximately 10,800 stores and clubs
                under 51 banners in 25 countries and eCommerce websites. With fiscal year 2021
                revenue of $559 billion, We employs over 2.2 million associates worldwide.
                Walmart continues to be a leader in sustainability, corporate philanthropy and employment opportunity.
                It’s all part of our unwavering commitment to creating opportunities and bringing value to customers and
                communities around the world.

            </p>
        </div>
    </div>
</div>
{% endblock %}
</html>

users/templates/onlinegrocery/base.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
  <meta charset="utf-8" />
  <title>{% block title %}Online Grocery{% endblock %}</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="{% static "css/base.css" %}" rel="stylesheet">
  <link href="{% static "css/main.css" %}" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="{% static 'javascript/base.js' %}"></script>
</head>
<body>


        <nav  class="navbar navbar-custom">
        <ul class="nav navbar-nav">

            <li><a href="{% url 'products:home' %}">Home</a></li>
            <li><a href="{% url 'users:about' %}">Our Story</a></li>
            <li><a href="{% url 'users:faq' %}">Faq</a></li>
            <li><a href="{% url 'products:visitor_new' %}">Contact</a></li>
            <li><a href="{% url 'cart:cart_detail' %}"><span class="glyphicon glyphicon-shopping-cart"></span></a></li>
        <li>

            <a href="#" class="glyphicon glyphicon-down" data-toggle="dropdown" role="button" aria-expanded="false">
            <span>All Categories</span>
            </a>

                        <ul class="dropdown-menu" role="menu">

{% for c in categories%}
        <li {% if category.slug == c.slug %}class="selected"{% endif %}>
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>


{% endfor %}


                        </ul>
            <li>

        </ul>
        <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="dropdown">

                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            <i class="glyphicon glyphicon-user"></i>
                            <span>{{ user.username }}</span>
                            <span class="caret"></span>
                        </a>

                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'users:edit_customer' pk=user.pk %}">Edit profile</a></li>
                            <li><a href="{% url 'password_change' %}">Change password</a></li>
                            <li><a href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>

                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-user"></span> Login | Signup</a></li>
                {% endif %}
            </ul>
    </nav>

  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

users/templates/onlinegrocery/categories_list.html
<!DOCTYPE html>
<html lang="en">
{% extends 'onlinegrocery/base.html' %}

{% block content %}

    <html>
    <head>
        <meta charset="UTF-8">
        <title> Grocery Shop | Categories list</title>
    </head>
    <body>

    <div class="row">
        <h2 class="headings">Categories list</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover custom-table" id="categories-list">
            <thead>
            <tr>
                <th>Categories</th>
                <th>Slug</th>
            </tr>
            </thead>
            <tbody>
            {% for category in categories %}
                <tr>
                    <td><a href="{% url 'products:category_edit' pk=category.pk %}">{{ category.name }}</a></td>
                    <td>{{ category.slug }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    </body>
    </html>
{% endblock %}
</html>

users/templates/onlinegrocery/category_delete.html
<!DOCTYPE html>
<html lang="en">
{% extends 'onlinegrocery/base.html' %}
{% block content %}
    <h1 class='headings' >Delete category</h1>
    <form method="post" class="custom-form">
        {% csrf_token %}
        <h4>Are you sure you want to delete the category : <b>{{ category.name }}</b></h4>
        <h5><span class="glyphicon glyphicon-warning-sign"></span> Attention !!! This action cannot be undone and you will lose the data forever!</h5>
        <div class="buttons-container">
            <input type="submit" class="btn btn-danger" value="Delete">
            <a href="{% url 'products:category_list_emp'  %}">Cancel</a>
        </div>
    </form>
{% endblock %}
</html>

users/templates/onlinegrocery/category_edit.html
<!DOCTYPE html>
<html lang="en">
{% extends 'onlinegrocery/base.html' %}
{% block content %}
    <h1 class="headings">Edit Category</h1>
    <form method="POST" class="custom-form">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="buttons-container">
            <button type="submit" class="save btn btn-default">Update</button>
            <a href="{% url 'products:category_delete' pk=pk %}" type="button" class="save btn btn-default">Delete</a>
        </div>
    </form>
{% endblock %}
</html>

users/templates/onlinegrocery/contact_page.html
<!DOCTYPE html>
 <html lang="en">
 {% extends 'onlinegrocery/base.html' %} 
 {% block content %} 
     <h1>BE IN TOUCH</h1>
     <p>If you don't see what you're looking for, or would like us to work with you on a custom design, feel free to be in touch!</p> 
    <form action="." method="post">
    {{ form.as_p }}
    <p><input type="submit" value="Submit"></p>
    {% csrf_token %}
  </form>
{% endblock %}

users/templates/onlinegrocery/employee_home.html
<!DOCTYPE html>
<html lang="en">
{% extends 'onlinegrocery/base.html' %}
{% load static %}
{% block content %}

   <body>
   {% if user.is_authenticated %}
       <div class="page-container">
           <h2 class="top-menu">Hello {{ user.username }},</h2>
           <p>Please choose from below options.</p>

       </div>
   {% endif %}
   <div class="content">
       <div class="row">
           <div class="col-md-12">
               <div class="links">
                   <!-- Example row of columns -->
                   <div class="row">
                       <div class="col-md-3">
                           <div class="thumbnail">
                               <div class="thumbnail-heading">
                                   <h3>Categories</h3>
                               </div>
                               <img src="{% static "img/Categories.png" %}" id="categories-img" alt="categories"/>
                               <div class="caption">
                                   <h4>Total number of categories : {{ context.categoryCount }}</h4>
                                   <a class="btn btn-primary" href="{% url 'products:category_new' %}"><span class="glyphicon glyphicon-plus"></span> Add</a>
                                   <a class="btn btn-primary" href="{% url 'products:category_list_emp' %}"><span class="glyphicon glyphicon-th-list"></span> View list</a>
                               </div>
                           </div>
                       </div>
                       <div class="col-md-3">
                           <div class="thumbnail">
                               <div class="thumbnail-heading">
                                    <h3>Products</h3>
                               </div>
                               <img src="{% static "img/Products.png" %}" alt="products"/>
                               <div class="caption">
                                   <h4>Total number of products : {{ context.productsCount }}</h4>
                                   <a class="btn btn-primary" href="{% url 'products:product_new' %}"><span class="glyphicon glyphicon-plus"></span> Add</a>
                                   <a class="btn btn-primary" href="{% url 'products:product_list' %}"><span class="glyphicon glyphicon-th-list"></span> View list</a>
                               </div>
                           </div>
                       </div>
                       <div class="col-md-3">
                           <div class="thumbnail">
                               <div class="thumbnail-heading">
                                    <h3>Customers</h3>
                               </div>
                               <img src="{% static "img/Customers.png" %}" alt="customers"/>
                               <div class="caption">
                                   <h4>Total number of customers : {{ context.customerCount }}</h4>
                                   <a class="btn btn-primary" href="{% url 'users:register_customer' %}"><span class="glyphicon glyphicon-plus"></span> Add</a>
                                   <a class="btn btn-primary" href="{% url 'users:customer_list' %}"><span class="glyphicon glyphicon-th-list"></span> View list</a>
                               </div>
                           </div>
                       </div>
                       <div class="col-md-3">
                           <div class="thumbnail">
                               <div class="thumbnail-heading">
                                    <h3>Orders</h3>
                               </div>
                               <img src="{% static "img/Orders.png" %}" alt="orders"/>
                               <div class="caption">
                                   <h4>Total number of orders : {{ context.orderCount }}</h4>
                                   <a class="btn btn-primary" href="{% url 'orders:order_list' %}"><span class="glyphicon glyphicon-th-list"></span> View list</a>
                               </div>
                           </div>
                       </div>
                   </div>
               </div>
           </div>
       </div>
   </div>
   </body>

{% endblock %}

</html>

users/templates/onlinegrocery/faq_page.html
<!DOCTYPE html>
<html lang="en">
{% extends 'onlinegrocery/base.html' %}
{% block content %}

<h1 class="headings">Frequently asked questions</h1>
<div>
    <h3>Returns</h3>
    <p>
        Q: What do I do if I don’t have my receipt?<br>
        We will accept a return or exchange without a receipt if:<br>
1. You present a valid, government-issued photo ID that has not been altered in any way.<br>
2. The refund verification process accepts the return. If an item is returned without a receipt and the refund verification process accepts it, you can:<br>
a. Exchange the item(s).
b. Get a cash refund if the refund value of the returned item(s) is less than $25<br>
        3. If you do not have your receipt or order number, the store may be able to look up your purchase if you have:<br>
a. The credit or debit card used to make the purchase in-store.<br>
b. The email or phone number used to make the purchase online.<br>
        Q: How will I be refunded?<br>
If you return an item within the allowable return period with a receipt, the refund will be applied to the original method of payment. If you made the purchase using:<br>
Cash or check: You’ll receive a cash refund.<br>
    </p>

</div>
{% endblock %}
</html>

users/templates/onlinegrocery/feedback_done.html
{% extends "onlinegrocery/base.html" %}
{% block title %}Thank you for your valuable feedback!{% endblock %}
{% block content %}
    <h1>Have a great day!</h1>
    <p>If you want to login, click here!<a href ="{% url 'users:home' %}">login here</a></p>
{% endblock %}

users/templates/onlinegrocery/list.html
{% extends "onlinegrocery/base.html" %}
{% load static %}

{% block title %}
  {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
  <div id="sidebar">
    <h3>Categories</h3>
    <ul>
      <li {% if not category %}class="selected"{% endif %}>
        <a href="{% url "products:product_list" %}">All</a>
      </li>
      {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected"{% endif %}>
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
  <div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
    <form method="GET" class="filter-form" id="product-filter">
      <span class="glyphicon glyphicon-filter"></span><span><b>Filters : </b></span>
        <div>
      {{ productFilter.form }}
      <input type="submit" value="Filter" class="btn btn-default"/>
        <input  type="submit" value="Clear" class="btn btn-default" onclick="resetform()">
    </div>
    </form>
    {% for product in products %}
      <div class="item">
        <div class="product-img-container">
            <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
            </a>
        </div>
      <div class="product-name">
            <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
            ${{ product.price }}
      </div>
      </div>
{#        <div class="card-columns">#}
{#        <div class="card-body">#}
{#            <a href="{{ product.get_absolute_url }}">#}
{#                <img src="{% if product.image %}{{ product.image.url }}#}
{#                          {% else %}{% static "img/no_image.png" %}{% endif %}">#}
{#            </a>#}
{#        </div>#}
{#        <div class="card-text">#}
{#            <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>#}
{#                ${{ product.price }}#}
{#        </div>#}
{#      </div>#}
    {% endfor %}
  </div>
{% endblock %}

users/templates/onlinegrocery/onlinegrocery_homepage.html
<!DOCTYPE html>
<html lang="en">
{% extends 'onlinegrocery/base.html' %}
{% load static %}

{% block content %}

</head>
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <img src="{% static "img/image1.png" %}" alt="freshfruits" width="500" alt="Fruits">
        <div class="carousel-caption">
            <nav2>

        <ul class="nav2">

            <li><a href="{% url 'products:product_list_by_category' %}">Shop Now </a></li>
            <h3>Fresh Fruits</h3>
        <p>Have fruits & vegetables if you want to lead a fruitful life!</p>
        </ul>


</nav2>

      </div>
    </div>

    <div class="item">
      <img src="{% static "img/image3.png" %}" alt="freshfruits" width="500" alt="milk">
        <div class="carousel-caption">
            <nav2>

        <ul class="nav2">

            <li><a href="{% url 'products:product_list' %}">Shop Now </a></li>


            <h3>Organic food</h3>
        <p>The first wealth is health!</p>
        </ul>


</nav2>

      </div>
    </div>

    <div class="item">
      <img src="{% static "img/image2.png" %}" alt="freshfruits" width="500" alt="Vegetables">
    <div class="carousel-caption">
        <nav2>

        <ul class="nav2">

            <li><a href="{% url 'products:product_list' %}">Shop Now </a></li>
           <h3>Fresh Vegetables</h3>
        <p>A healthy outside starts from the inside!</p>
        </ul>


</nav2>

      </div>
  </div>




<center>



    </div>



{% endblock %}

</html>

users/templates/onlinegrocery/product_delete.html
<!DOCTYPE html>
<html lang="en">
{% extends 'onlinegrocery/base.html' %}
{% block content %}
    <h1 class='headings' >Delete product</h1>
    <form method="post" class="custom-form">
        {% csrf_token %}
        <h4>Are you sure you want to delete the category : <b>{{ product.name }}</b></h4>
        <h5><span class="glyphicon glyphicon-warning-sign"></span> Attention !!! This action cannot be undone and you will lose the data forever!</h5>
        <div class="buttons-container">
            <input type="submit" class="btn btn-danger" value="Delete">
            <a href="{% url 'products:product_list'  %}">Cancel</a>
        </div>

    </form>

{% endblock %}

</html>

users/templates/onlinegrocery/product_edit.html
<!DOCTYPE html>
<html lang="en">
{% extends 'onlinegrocery/base.html' %}
{% block content %}
    <h1 class="headings">Edit Product</h1>
    <form method="POST" class="custom-form">{% csrf_token %}
        {{ form.as_p }}
        <div class="buttons-container">
            <button type="submit" class="save btn btn-default">Update</button>
        </div>
    </form>
{% endblock %}
</html>

users/templates/onlinegrocery/product_new.html
<!DOCTYPE html>
<html lang="en">
{% extends 'onlinegrocery/base.html' %}
{% block content %}
    <h1 class="headings">Add a New Product</h1>
    <form method="POST" class="custom-form" enctype="multipart/form-data">{% csrf_token %}
          {{ form.as_p }}
        <div class="buttons-container">
            <button type="submit" class="save btn btn-default">Save</button>
        </div>
    </form>
{% endblock %}

</html>